### ISSUE TITLE
dependency on ember-cli-release

### ISSUE THREAD

**Issue by bmeurant** [offirgolan/ember-addon-genie#3]
`ember-cli-release` is a wonderfull tool but I am wondering why `ember-addon-genie` is currently forcing users to install it.

I think it could make sense to only include it when it is necessary (`ember-cli-changelog` & `ember-cli-github-pages` ?) and not in `genie-init` blueprint.

A corollary question is "when does this addon is really required ?". It is a direct dependency of `ember-cli-changelog` and, maybe it does not have to be installed explicitely before. But maybe this is necessary for config update or something ...

Does it make sense to install & use `ember-cli-github-pages` without `ember-cli-release` as well ?

Maybe `ember-cli-release` could take place in a dedicated blueprint or be proposed as a dynamic choice when the user is generating a concerned blueprint? 

These are open questions :smirk:

**Comment by offirgolan** [comment]
In all honesty, I was force installing ember-cli-release to make sure its updated to the latest version. ember-cli-release is included in the default addon blueprint so I didnt think too much of it.

Is there a reason you dont want ember-cli-release installed?

**Comment by bmeurant** [comment]
Hi,

No, I have no reason to not want `ember-cli-release` and, good, point, I did not noticed it was part of the standard addon blueprint.

But I am using `ember-addon-genie` blueprints one by one (not the all in one `ember-addon-genie`) and I'd like each task would be properly isolated and do not install non related dependencies.  

In fact, I am ok if `genie-init` installs (updates) `ember-cli-release` (which is, as you said, part of the default blueprint) but I am more concerned by the fact that it also create `config/release.js` file. AFAIK, this file is not created by `ember addon` and I'd really like to avoid forcing users creating / committing files that they do not necessarily use or even know.

**Comment by offirgolan** [comment]
@bmeurant I've made the changes you mentioned! Thanks for the feedback 😄
